Practice.all.destroy_all
Verse.all.destroy_all

Verse.create(ref_id: 1, chapter: 1, verse: 1, text:  "The proverbs of Solomon son of David, king of Israel:")
Verse.create(ref_id: 2, chapter: 1, verse: 2, text:  "for gaining wisdom and instruction; for understanding words of insight;")
Verse.create(ref_id: 3, chapter: 1, verse: 3, text:  "for receiving instruction in prudent behavior, doing what is right and just and fair;")
Verse.create(ref_id: 4, chapter: 1, verse: 4, text:  "for giving prudence to those who are simple, knowledge and discretion to the young—")
Verse.create(ref_id: 5, chapter: 1, verse: 5, text:  "let the wise listen and add to their learning, and let the discerning get guidance—")
Verse.create(ref_id: 6, chapter: 1, verse: 6, text:  "for understanding proverbs and parables, the sayings and riddles of the wise.")
Verse.create(ref_id: 7, chapter: 1, verse: 7, text:  "The fear of the Lord is the beginning of knowledge, but fools despise wisdom and instruction.")
Verse.create(ref_id: 8, chapter: 1, verse: 8, text:  "Listen, my son, to your father’s instruction and do not forsake your mother’s teaching.")
Verse.create(ref_id: 9, chapter: 1, verse: 9, text:  "They are a garland to grace your head and a chain to adorn your neck.")
Verse.create(ref_id: 10, chapter: 1, verse: 10, text:  "My son, if sinful men entice you, do not give in to them.")
Verse.create(ref_id: 11, chapter: 1, verse: 11, text:  "If they say, 'Come along with us; let’s lie in wait for innocent blood, let’s ambush some harmless soul;")
Verse.create(ref_id: 12, chapter: 1, verse: 12, text:  "let’s swallow them alive, like the grave, and whole, like those who go down to the pit;")
Verse.create(ref_id: 13, chapter: 1, verse: 13, text:  "we will get all sorts of valuable things and fill our houses with plunder;")
Verse.create(ref_id: 14, chapter: 1, verse: 14, text:  "cast lots with us; we will all share the loot'—")
Verse.create(ref_id: 15, chapter: 1, verse: 15, text:  "my son, do not go along with them, do not set foot on their paths;")
Verse.create(ref_id: 16, chapter: 1, verse: 16, text:  "for their feet rush into evil, they are swift to shed blood.")
Verse.create(ref_id: 17, chapter: 1, verse: 17, text:  "How useless to spread a net where every bird can see it!")
Verse.create(ref_id: 18, chapter: 1, verse: 18, text:  "These men lie in wait for their own blood; they ambush only themselves!")
Verse.create(ref_id: 19, chapter: 1, verse: 19, text:  "Such are the paths of all who go after ill-gotten gain; it takes away the life of those who get it. Wisdom's Rebuke")
Verse.create(ref_id: 20, chapter: 1, verse: 20, text:  "Out in the open wisdom calls aloud, she raises her voice in the public square;")
Verse.create(ref_id: 21, chapter: 1, verse: 21, text:  "on top of the wall she cries out, at the city gate she makes her speech:")
Verse.create(ref_id: 22, chapter: 1, verse: 22, text:  "'How long will you who are simple love your simple ways? How long will mockers delight in mockery and fools hate knowledge?")
Verse.create(ref_id: 23, chapter: 1, verse: 23, text:  "Repent at my rebuke! Then I will pour out my thoughts to you, I will make known to you my teachings.")
Verse.create(ref_id: 24, chapter: 1, verse: 24, text:  "But since you refuse to listen when I call and no one pays attention when I stretch out my hand,")
Verse.create(ref_id: 25, chapter: 1, verse: 25, text:  "since you disregard all my advice and do not accept my rebuke,")
Verse.create(ref_id: 26, chapter: 1, verse: 26, text:  "I in turn will laugh when disaster strikes you; I will mock when calamity overtakes you—")
Verse.create(ref_id: 27, chapter: 1, verse: 27, text:  "when calamity overtakes you like a storm, when disaster sweeps over you like a whirlwind, when distress and trouble overwhelm you.")
Verse.create(ref_id: 28, chapter: 1, verse: 28, text:  "Then they will call to me but I will not answer; they will look for me but will not find me,")
Verse.create(ref_id: 29, chapter: 1, verse: 29, text:  "since they hated knowledge and did not choose to fear the Lord.")
Verse.create(ref_id: 30, chapter: 1, verse: 30, text:  "Since they would not accept my advice and spurned my rebuke,")
Verse.create(ref_id: 31, chapter: 1, verse: 31, text:  "they will eat the fruit of their ways and be filled with the fruit of their schemes.")
Verse.create(ref_id: 32, chapter: 1, verse: 32, text:  "For the waywardness of the simple will kill them, and the complacency of fools will destroy them;")
Verse.create(ref_id: 33, chapter: 1, verse: 33, text:  "but whoever listens to me will live in safety and be at ease, without fear of harm.'")
Verse.create(ref_id: 34, chapter: 2, verse: 1, text: "My son, if you accept my words and store up my commands within you,")
Verse.create(ref_id: 35, chapter: 2, verse: 2, text: "turning your ear to wisdom and applying your heart to understanding—")
Verse.create(ref_id: 36, chapter: 2, verse: 3, text: "indeed, if you call out for insight and cry aloud for understanding,")
Verse.create(ref_id: 37, chapter: 2, verse: 4, text: "and if you look for it as for silver and search for it as for hidden treasure,")
Verse.create(ref_id: 38, chapter: 2, verse: 5, text: "then you will understand the fear of the Lord and find the knowledge of God.")
Verse.create(ref_id: 39, chapter: 2, verse: 6, text: "For the Lord gives wisdom; from his mouth come knowledge and understanding.")
Verse.create(ref_id: 40, chapter: 2, verse: 7, text: "He holds success in store for the upright, he is a shield to those whose walk is blameless,")
Verse.create(ref_id: 41, chapter: 2, verse: 8, text: "for he guards the course of the just and protects the way of his faithful ones.")
Verse.create(ref_id: 42, chapter: 2, verse: 9, text: "Then you will understand what is right and just and fair—every good path.")
Verse.create(ref_id: 43, chapter: 2, verse: 10, text: "For wisdom will enter your heart, and knowledge will be pleasant to your soul.")
Verse.create(ref_id: 44, chapter: 2, verse: 11, text: "Discretion will protect you, and understanding will guard you.")
Verse.create(ref_id: 45, chapter: 2, verse: 12, text: "Wisdom will save you from the ways of wicked men, from men whose words are perverse,")
Verse.create(ref_id: 46, chapter: 2, verse: 13, text: "who have left the straight paths to walk in dark ways,")
Verse.create(ref_id: 47, chapter: 2, verse: 14, text: "who delight in doing wrong and rejoice in the perverseness of evil,")
Verse.create(ref_id: 48, chapter: 2, verse: 15, text: "whose paths are crooked and who are devious in their ways.")
Verse.create(ref_id: 49, chapter: 2, verse: 16, text: "Wisdom will save you also from the adulterous woman, from the wayward woman with her seductive words,")
Verse.create(ref_id: 50, chapter: 2, verse: 17, text: "who has left the partner of her youth and ignored the covenant she made before God.[a]")
Verse.create(ref_id: 51, chapter: 2, verse: 18, text: "Surely her house leads down to death and her paths to the spirits of the dead.")
Verse.create(ref_id: 52, chapter: 2, verse: 19, text: "None who go to her return or attain the paths of life.")
Verse.create(ref_id: 53, chapter: 2, verse: 20, text: "Thus you will walk in the ways of the good and keep to the paths of the righteous.")
Verse.create(ref_id: 54, chapter: 2, verse: 21, text: "For the upright will live in the land, and the blameless will remain in it;")
Verse.create(ref_id: 55, chapter: 2, verse: 22, text: "but the wicked will be cut off from the land, and the unfaithful will be torn from it.")

Practice.create(title: 'read the chapter', body: 'Take 5 minutes to read the chapter', example: '');
Practice.create(title: 'listen to the chapter', body: 'If you have you version bible it has an audio portion you can listen to a fancy English accented man serenade you with tasty wisdom nuggets', example: '');
Practice.create(title: 'read 10 verses, twice', body: 'Focus on 10 verses and read them two times', example: 'read verses 1 - 10, then re-read them.');
Practice.create(title: 'read 5 verses, three times', body: 'Focus on 5 verses and read them three times.', example: 'read verses 1 - 5, then re-read them 2 more times.');
Practice.create(title: 'focus on current verse', body: 'Each verse can usually be broken down to 2 or 3 parts.', example: 'Verse 1 is 2 parts. So Parent start with part 1 and say "The proverbs of Solomon." Then, let your child say that part 1 back to you. Give them a few moments to process each word before giving them the next word. Go back and forth saying that to each other, 5 times.');

puts 'SEEDED!'
