# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Verse.create(chapter: 1, verse: 1, text:  "The proverbs of Solomon son of David, king of Israel:")
Verse.create(chapter: 1, verse: 2, text:  "for gaining wisdom and instruction; for understanding words of insight;")
Verse.create(chapter: 1, verse: 3, text:  "for receiving instruction in prudent behavior, doing what is right and just and fair;")
Verse.create(chapter: 1, verse: 4, text:  "for giving prudence to those who are simple, knowledge and discretion to the young—")
Verse.create(chapter: 1, verse: 5, text:  "let the wise listen and add to their learning, and let the discerning get guidance—")
Verse.create(chapter: 1, verse: 6, text:  "for understanding proverbs and parables, the sayings and riddles of the wise.")
Verse.create(chapter: 1, verse: 7, text:  "The fear of the Lord is the beginning of knowledge, but fools despise wisdom and instruction.")
Verse.create(chapter: 1, verse: 8, text:  "Listen, my son, to your father’s instruction and do not forsake your mother’s teaching.")
Verse.create(chapter: 1, verse: 9, text:  "They are a garland to grace your head and a chain to adorn your neck.")
Verse.create(chapter: 1, verse: 10, text:  "My son, if sinful men entice you, do not give in to them.")
Verse.create(chapter: 1, verse: 11, text:  "If they say, 'Come along with us; let’s lie in wait for innocent blood, let’s ambush some harmless soul;")
Verse.create(chapter: 1, verse: 12, text:  "let’s swallow them alive, like the grave, and whole, like those who go down to the pit;")
Verse.create(chapter: 1, verse: 13, text:  "we will get all sorts of valuable things and fill our houses with plunder;")
Verse.create(chapter: 1, verse: 14, text:  "cast lots with us; we will all share the loot'—")
Verse.create(chapter: 1, verse: 15, text:  "my son, do not go along with them, do not set foot on their paths;")
Verse.create(chapter: 1, verse: 16, text:  "for their feet rush into evil, they are swift to shed blood.")
Verse.create(chapter: 1, verse: 17, text:  "How useless to spread a net where every bird can see it!")
Verse.create(chapter: 1, verse: 18, text:  "These men lie in wait for their own blood; they ambush only themselves!")
Verse.create(chapter: 1, verse: 19, text:  "Such are the paths of all who go after ill-gotten gain; it takes away the life of those who get it. Wisdom's Rebuke")
Verse.create(chapter: 1, verse: 20, text:  "Out in the open wisdom calls aloud, she raises her voice in the public square;")
Verse.create(chapter: 1, verse: 21, text:  "on top of the wall she cries out, at the city gate she makes her speech:")
Verse.create(chapter: 1, verse: 22, text:  "'How long will you who are simple love your simple ways? How long will mockers delight in mockery and fools hate knowledge?")
Verse.create(chapter: 1, verse: 23, text:  "Repent at my rebuke! Then I will pour out my thoughts to you, I will make known to you my teachings.")
Verse.create(chapter: 1, verse: 24, text:  "But since you refuse to listen when I call and no one pays attention when I stretch out my hand,")
Verse.create(chapter: 1, verse: 25, text:  "since you disregard all my advice and do not accept my rebuke,")
Verse.create(chapter: 1, verse: 26, text:  "I in turn will laugh when disaster strikes you; I will mock when calamity overtakes you—")
Verse.create(chapter: 1, verse: 27, text:  "when calamity overtakes you like a storm, when disaster sweeps over you like a whirlwind, when distress and trouble overwhelm you.")
Verse.create(chapter: 1, verse: 28, text:  "Then they will call to me but I will not answer; they will look for me but will not find me,")
Verse.create(chapter: 1, verse: 29, text:  "since they hated knowledge and did not choose to fear the Lord.")
Verse.create(chapter: 1, verse: 30, text:  "Since they would not accept my advice and spurned my rebuke,")
Verse.create(chapter: 1, verse: 31, text:  "they will eat the fruit of their ways and be filled with the fruit of their schemes.")
Verse.create(chapter: 1, verse: 32, text:  "For the waywardness of the simple will kill them, and the complacency of fools will destroy them;")
Verse.create(chapter: 1, verse: 33, text:  "but whoever listens to me will live in safety and be at ease, without fear of harm.'")
